title: "Alex Loo Hui Jian | Systems & Architecture Notes"
description: "Notes on Mechanical Sympathy and Systems Engineering"
theme: minima
header_pages:
  - index.md
  - projects/project-duckrag-SAD.md
